name: Integrate

on: [push]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: First
      - uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - run: node script.js
      run: echo Hello